### ISSUE TITLE
Hotword detection stops working when no command is given

### ISSUE THREAD

**Issue by yusefasjana** [eouia/MMM-Assistant#12]
I was able to successfully install the module and trigger a couple of commands but I'm having an issue when I trigger the Hotword and I head the ding but don't follow up with a command then the hotword detection stops working entirely. 

I checked the logs but didn't see any errors.

Thanks for your help.

**Comment by eouia** [comment]
Sorry. I was in my business works, so I couldn't catch your issue.
Hmmmm, I didn't assume there was no command after activation.
Maybe I can add some routine for checking. Plz wait for a while.

**Comment by afroguys** [comment]
how to change the hotword from snowboy to others? just replace all .umdl file??

**Comment by eouia** [comment]
@afroguys replace `.umdl` to another `.umdl` or `.pmdl`.
Warning; making a proper `.pmdl` is not so easy. You should read Snowboy manual carefully before trying.

**Comment by E3V3A** [comment]
@yusefasjana @eouia  Is this still an issue?

**Comment by E3V3A** [comment]
Just FYI. 
I just created a `*.pmdl` from the kitt.ai/snowboy site and replaced the default `*.umdl`. Works great!
So those files are the same format, but different training sets. (Your own versus lots of people saying anything!)
