### ISSUE TITLE
Assistant langages

### ISSUE THREAD

**Issue by normyx** [eouia/MMM-Assistant#15]
Hi,

Is there a way to set another language for the assistant (snowboy) ? The language settings seems to be only for commands.
KR

**Comment by eouia** [comment]
New API could do that. It was released a month ago. I'll update in a few days or weeks. (Sorry, I should do my real life job first before this.)

**Comment by normyx** [comment]
Yes, I've seen it, the google-assistant seems to do it from new config parameters in release 0.2.x. I will try to do it, but I am not confortable with node, so if code needs to be modified, I will probably fail !
Regards

**Comment by normyx** [comment]
Hi eouia,
I've upgraded the google-assistant version to 0.2.2, rebuild all the stuff, and do the following modification and it works fine in french :
`config.js`
`            assistant: {
                auth: {
                    keyFilePath: "/home/pi/MagicMirror/modules/MMM-Assistant/secret.json", //When you want to change the location of this file, set this.
                    savedTokensPath: "/home/pi/MagicMirror/modules/MMM-Assistant/resources/tokens.js", //When you want to change the location of this file, set this.
                },
                conversation: {
                    lang: 'fr-FR',
                    audio: {
                        encodingIn: "LINEAR16", //Ignore this. I think you don't need to change this.
                        sampleRateOut: 16000, //Ignore this. I think you don't need to change this.
                    },
                },
            },
`

`node_helper.js`: line 229
`const assistant = new GoogleAssistant(this.config.assistant.auth)`
`node_helper.js`: line 246
`              = spokenResponseLength / (this.config.assistant.conversation.audio.sampleRateOut * 16 / 8) * 1000;
`
`node_helper.js`: line 307
`sampleRate: this.config.assistant.conversation.audio.sampleRateOut,`
`node_helper.js`: line 321
`assistant.start(this.config.assistant.conversation)`

The default config will probably need to be updated too.
I did not want to update your code.
Thx

**Comment by eouia** [comment]
Very thanks to your experimental trial. I'll reference your code in my next update. Thanks again.

**Comment by E3V3A** [comment]
@normyx  Can you enclose that code in proper code tags, triple back-ticks (```), please?

**Comment by E3V3A** [comment]
This is implemented by PR https://github.com/eouia/MMM-Assistant/pull/29
We need to check and merge.

@eouia  Can you test it?

**Comment by E3V3A** [comment]
Implemented in todays commits.
