### ISSUE TITLE
email is required

### ISSUE THREAD

**Issue by TheCrack3r** [eouia/MMM-Assistant#17]
Hi Eouia

Thanks for this fantastic Module.

But i have a problem, when I start the MagicMirror (npm start) it starts and it records but he stops after i said "Smart Mirror" or "Snowboy".  

Thats the Error:

```
[Auth error:Error: email is required.
Recording 4000 bytes
[ASSTNT] RecognizeStream Error:  { Error: 14 UNAVAILABLE: Getting metadata from plugin failed 
with error: email is required.
    at createStatusError (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:248:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:804:12
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Getting metadata from plugin failed with error: email is required.' }
Recording 4000 bytes
Recording 4000 bytes
(node:1677) Warning: No such label 'End Recording' for console.timeEnd()
```

Do you know something about this?

Thanks
TheCrack3r

**Comment by eouia** [comment]
I think you've failed or missed something on getting google API permission. (Try again.)

**Comment by TheCrack3r** [comment]
Hii eouia. I have removed the MMM-Assistant folder and i have installed from 1-4 but i have a question. In the config i must fill the Google project id and the Keyfilename. But i dont know which keyfilename.

**Comment by TheCrack3r** [comment]
Snowboy works but smart mirror not. Why?

**Comment by eouia** [comment]
Your `keyfilename` is similiar with `YOURPROJECTNAME-SOMETHINGHEXCODE.json`. You can get that file in `https://console.cloud.google.com/apis/credentials?project=YOUR-PROJECT ...` by `Create confidentials`
That filename might be too long to handle. you can just rename it like `servicekey.json` or anything, and put that file in your `/resources` directory and put that info in your config file. I think it would work.

**Comment by TheCrack3r** [comment]
Yes. Thank you very much. It works. But i have an other problem. I can not switch language. I write de-DE but it does not speak on german.

**Comment by eouia** [comment]
for Google Assistant, New APIModule which was released a few months ago could help that, but currently, I haven't updated it due to lack of my time. 

You can update it by yourself. modify `"google-assistant": "0.1.12",` in `package.json` to `"0.2.2"`. I didn't test but I think it could work.

**Comment by E3V3A** [comment]
@TheCrack3r  
Please open a new issue for German language support, or help us out by filing a PR.
Thank you!
