### ISSUE TITLE
MMM-Assistant is unable to wake up after Hotkey command (Snowboy/Smart Mirror)

### ISSUE THREAD

**Issue by werdnllac** [eouia/MMM-Assistant#19]
I had followed every step https://github.com/eouia/MMM-Assistant/wiki and everything went smoothly until 3-2) .pmdl for snowboy hotword detection. Instruction was to visit https://snowboy.kitt.ai/ and get .pmdl for your voice. (Hotkey)

I tried following instruction at snowboy site - http://docs.kitt.ai/snowboy/ and instruction is really not clear how to get the command in. Now I am stuck here.

I also tried npm start command and there are numerous error with "npm ERR! enoent ENOENT: no such file or directory, open 'home/pi/package.json' (Where can I get this file or which step had I missed).

Please help

**Comment by eouia** [comment]
using `.pmdl` is optional. you can use default 2 `.umdl` without problem. and making proper `.pmdl` is REALLY hard to work.
`npm start...` means `step 4`?

**Comment by afroguys** [comment]
can i change the hotwork from _snowboy_ to other hotwork?? how to do that?

**Comment by eouia** [comment]
@afroguys 
1) use another `.umdl` (if there is). you can get `.umdl` from snowboy site.

2) make your own `.pmdl`.
You should make your `.pmdl` in your target device. it means you should record your voice in Raspberry Pi with snowboy tool(site). You cannot use `.pmdl` made once on the different device. Anyway, `.pmdl` on RPI is not so well working, I think...

**Comment by afroguys** [comment]
@eouia 
you mean i need to clone snowboy on rpi and start recording my voice.

i see at snowboy web, that we can create a hotword and start recording at the site. 

actually, i cannot find any demo or tutorial regarding snowboy at youtube, but i will try to create 1 hotword at snowboy web

**Comment by eouia** [comment]
@afroguys 
https://snowboy.kitt.ai/
After login, you can create your own howord `.pmdl` and download it.
But you should do that on your target device (Your MagicMirror RPI). If you make your `.pmdl` on your PC and move to RPI, it won't work.

**Comment by afroguys** [comment]
ok. thank you.

**Comment by werdnllac** [comment]
Thank you.
I have managed to create the hotwords. As per instructed 

_3-2) .pmdl for snowboy hotword detection.
This module needs 2 hotword models at least, one for activating Google-Assistant mode and the other for activating voice-commander mode. By default, smart_mirror.umdl and snowboy.umdl universal models(.umdl)are provided._

Thereafter, I execute the command 
"**cd <Your MagicMirror Direcotry>/modules/MMM-Assistant
npm install --save-dev electron-rebuild && ./node_modules/.bin/electron-rebuild --pre-gyp-fix**"

And I tried inserting "Configuration" (Both Simple & Full Version) in config.js. Both don't work. 

Both Simple and Full Version doesn't work. The MagicMirror turn blank and despite pressing Ctrl+Q, it doesn't exit from MagicMirror.

Please advice

**Comment by E3V3A** [comment]
Hi @werdnllac !
Did you follow the installation instructions? Eh, yeah, I know they're a bit lacking, we're on it, but we need at least to see what error you get.  

1. Please post the output of the following: 
```bash
uname -a
sudo lsb_release -a
dmesg |grep OF:
dmesg |grep Firmware
dpkg --print-architecture

# Get the nodejs and npm versions
node -v && npm -v
```

2. Then post the commands you tried and their output. Enclose your pasted results in triple back-ticks (```). 

PS. CTRL-Q is not how you stop anything, it's `CTRL-C`.

**Comment by werdnllac** [comment]
Hi @E3V3A 

Thanks for the guidance. The following is the result:

uname -a
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux

sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

dmesg |grep OF:
[    0.000000] OF: fdt:Machine model: Raspberry Pi 3 Model B Rev 1.2

dmesg |grep Firmware
[    4.738002] brcmfmac: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f

dpkg --print-architecture
armhf

# Get the nodejs and npm versions
node -v && npm -v
v6.13.1
3.10.10

**Comment by werdnllac** [comment]
PS: I tried Ctrl + C won't help anything. When my MagicMirror executed, the screen turn to a total black screen, I couldn't exit back to the Desktop interface.

**Comment by E3V3A** [comment]
@werdnllac 
Your setup look good, but you need to update your *nodejs* and *npm* versions! They should be: 
```
v9.8.0
5.7.1
```
Please google the raspberry stackexchange or forums on how to do that. Then reinstall MM from the beginning. (Just to make sure we're on the same page.) It should be a quick operation as you already know what to do. Copy/paste right? If you already have a working configuration, you can make a backup copy of that first. Then make sure MM is running with default modules. (Sorry, we can't help you with basic MM installation here.) 

Finally, come back here and file a new issue, if any, and clearly stating what is the error you get and what your pm2 logs say. 
```bash
cat  ~/.pm2/logs/mm-out-0.log
cat ~/.pm2/logs/mm-error-0.log
```

Your MM config file is in `~/MagicMirror/config/config.js` and you should only have **one** of the module config version in it.

**Comment by E3V3A** [comment]
@werdnllac 
If your issue is resolved, please let us know so we can close this. 
Thank you.

**Comment by werdnllac** [comment]
Thanks @E3V3A 

Please keep this post open as I had a pretty decent MM at the moment (as shown in screenshot). Hence, I will need to redo the entire MM with a fresh new SDcard before I can try and continue further development in it.

Please give me sometime. Thanks

**Comment by werdnllac** [comment]
![mmcapture](https://user-images.githubusercontent.com/36906837/37962143-ca86c0e0-31ec-11e8-9151-062a3f2761cb.PNG)

**Comment by E3V3A** [comment]
@werdnllac  
Thanks for getting back to us. I'll close this for now as we've done some significant api version changes.
You can re-open when you're back and ready.
Cheers!
