### ISSUE TITLE
I have a question about google cloud vision api in magic mirror

### ISSUE THREAD

**Issue by Simchaelin** [eouia/MMM-Assistant#21]
I am having difficulty making a module of google vision api as a module. Do I have to make a file like google-auth.js like the MMM-Assistant and auth: {} in config? And if you write const vision = require ('@ google-cloud / vision'); in node_helper.js, you will get the error: Failed to load gRPC binary modules because it was not installed for the current system. Please help me

**Comment by eouia** [comment]
Sorry. I have no idea about Google Vision API. So I cannot help about it.
your error means you need dependencies for your module. your `vision` and other dependencies are should be installed already in your `node_modules` directory or globally. Study how to use `npm` and `package.json`.

**Comment by Simchaelin** [comment]
Thank you !! I solved the problems!!
