### ISSUE TITLE
snowboy (GA) wake word poorly detected

### ISSUE THREAD

**Issue by E3V3A** [eouia/MMM-Assistant#26]
While the `smart mirror` wake word is very well detected, the `snowboy` is not. 

My guess is that one reason could be that many people with very different accents have recorded this in the snowboy library. 

How can I improve the detection?

**Comment by eouia** [comment]
@E3V3A No idea about it. I thought always that was due to my pronunciation as a foreigner.

**Comment by E3V3A** [comment]
Do you know how to train the Snowboy words? I think we just have a crappy model.

**Comment by E3V3A** [comment]
I just created a `*.pmdl` from the kitt.ai/snowboy site and replaced the default `*.umdl`. Works great!
So those files are the same format, but different training sets. (Your own versus lots of people saying anything!)
