### ISSUE TITLE
Can we merge the Alexa branch to Master?

### ISSUE THREAD

**Issue by E3V3A** [eouia/MMM-Assistant#27]
It would be fantastic to have the Alexa functionality built-in to the GA, MM master branch. 

@eouia What would it take to do so? (I.e. how different is the code?)

**Comment by E3V3A** [comment]
???

**Comment by eouia** [comment]
Alexa branch is not working version. frankly, it is just a copy of original of past. I tried to develop Integration of Alexa and it was halted. Because from that time I started to lose my concentration a bit.

**Comment by E3V3A** [comment]
Thanks. Good to know. What would you see as challenge to do this?

**Comment by E3V3A** [comment]
@eouia 
Ok, let's remove that branch. Do you know how to do it? OR should I do it?

**Comment by E3V3A** [comment]
Alexa branch removed.
