### ISSUE TITLE
Error: The incoming JSON object does not contain a client_email field (solved)

### ISSUE THREAD

**Issue by drftg** [eouia/MMM-Assistant#50]
The "MIRROR" hot word throws the error on the console and then MMM-Assistant stops working
The "ASSISTANT" hot word works perfect.

**Behaviour**

`npm start`
```
Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Assistant
No helper found for module: clock.
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-Assistant
Sockets connected & modules started ...
Launching application.
[ASSTNT] Snowboy Activated

<saying "snowboy">

[ASSTNT] Assistant Activated

<saying "what time is it">

[ASSTNT] GA Transcription:  { transcription: 'what', done: false }
[ASSTNT] GA Transcription:  { transcription: 'what time', done: false }
[ASSTNT] GA Transcription:  { transcription: 'what time is', done: false }
[ASSTNT] GA Transcription:  { transcription: 'what time is it', done: false }
[ASSTNT] GA Transcription:  { transcription: 'what time is it', done: true }

`correct response`

[ASSTNT] Snowboy Activated

<saying "smart mirror">

Whoops! There was an uncaught exception...

Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-auth-library/build/src/auth/jwtclient.js:218:19)
    at GoogleAuth.fromJSON (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-auth-library/build/src/auth/googleauth.js:380:16)
    at fs.readFile.e (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-auto-auth/index.js:125:48)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**checks**

```bash
# ls -ali assets`
config.txt  
google-access-tokens.json  
google-client-secret.json  
google-private-key.json
```
`node google-auth.js`
Google Authentication OK! Press CTRL+C to Quit.

config.js exactly like config.txt
Commenting out the

**Comment by E3V3A** [comment]
@drftg 
Please run the following command and check that your JSON output matches mine.

```bash
# for x in `ls -1 *.json`; do echo -e "\nFile: $x\n"; cat $x |sed -re "s/,/,\n/g" |sed -rz 's/\n+/\n/g'; echo -e "\n----"; done;

File: google-access-tokens.json

{"access_token":"ya29...X",
"refresh_token":"1/O...Qz",
"token_type":"Bearer",
"expiry_date":15......23}
----

File: google-client-secret.json

{"installed":{"client_id":"10.....apps.googleusercontent.com",
"project_id":"mmm-a-....",
"auth_uri":"https://accounts.google.com/o/oauth2/auth",
"token_uri":"https://accounts.google.com/o/oauth2/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"S....M",
"redirect_uris":["urn:ietf:wg:oauth:2.0:oob",
"http://localhost"]}}
----

File: google-private-key.json

{
  "type": "service_account",
  "project_id": "mmm-...",
  "private_key_id": "56....02",
  "private_key": "-----BEGIN PRIVATE KEY-----....=\n-----END PRIVATE KEY-----\n",
  "client_email": "mmm-...@appspot.gserviceaccount.com",
  "client_id": "11....87",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mmm-....%40appspot.gserviceaccount.com"
}
----
```
As you can see, there is only one place where there is an "email" field, but that one is auto-generated from the google developer console (or whatever it is called), when you export that file. 

There the `client_email` is the **`<project_id>@appspot.gserviceaccount.com`**. 

Please report your findings.

**Comment by drftg** [comment]
On my system those same files are present with a similar content. Somehow the error does not seem related to the actual files. renaming them result in the same error. Apparently there is another json file being processed ...?

**Comment by E3V3A** [comment]
please do a `git pull`, to see if that helps. It seem that your clone is not completely up-to-date with mine.

**Comment by drftg** [comment]
Started all over again with a new clone. Put all necessary files in the assets folder. Same error.

Then I modified the config.js file by adding an email address in this section:
```
stt: {
    auth: [{  // You can use multiple accounts to save money
        projectId:   'projectid', // REQUIRED (Google Voice API) -- project_id
        email: "service@projectid.iam.gserviceaccount.com", // same email as in google-private-key.json
        keyFilename: '/home/pi/MagicMirror/modules/MMM-Assistant/assets/google-private-key.json'  // REQUIRED ($
    }],
```
but then the following errors occur

Auth error:SyntaxError: Unexpected token
 in JSON at position 170
[ASSTNT] RecognizeStream Error:  { Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Unexpected token
 in JSON at position 170
    at createStatusError (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:248:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:804:12
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Getting metadata from plugin failed with error: Unexpected token \n in JSON at position 170' }

**Comment by E3V3A** [comment]
@drftg You shouldn't need any email in config. I have no idea how you got to this point...

**Comment by E3V3A** [comment]
Oh man , this is a PITA. 
It seem google keep changing shit around.

Just FYI:
* You require to give google some credit card data to get your account up, unless you got that already?
* Check this link how to setup a lot of stuff:  
  https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account

TBA

**Comment by drftg** [comment]
I have given up. Tried many many things as well as all your suggestions. If it is an authentication thing then I guess the error messages just get swallowed up somewhere out of my reach.

**Comment by drftg** [comment]
I could not let it rest. So I made a new project and created all "assets" again. This time the Unexpected token was at position 166. It was then I realized there really was an Unexpected token present in the file google-private-key.json! During clipboard use on my Windows system 2 line feeds where introduced in the private key section (invisible in nano, very visible in vi). After removing them everything finally works!

**Comment by E3V3A** [comment]
@drftg 
I'm very happy you managed to fix it! Anyone else? 

**`During clipboard use on my Windows system, 2 line feeds where introduced in the private key section (invisible in nano)`**

Yeah, copy/paste from any window can be tricky!  
I've seen other issues, where parts have either been missing or replaced.
