### ISSUE TITLE
Google Assistant is not responding 

### ISSUE THREAD

**Issue by FLASH980** [eouia/MMM-Assistant#51]
Hey , i followed the installation steps, 

the module is detecting the launch phrase perfectly  and performs the" Smart Mirror" commands perfectly as well , but Google Assistant commands are not performed ,  it only says "**give me permission to help you**". 

I checked my Google API analytics and I found that Cloud Speech API requests are all successful  but Google Assistant API are all ERRORS 

![image](https://user-images.githubusercontent.com/18060339/38497787-e0df1fa4-3c0a-11e8-8361-0fbd58cfc852.png)

NPM version 
`3.10.10`

node version 
`v6.14.1`
uname -a
```
Linux raspberrypi 4.14.31-v7+ #1104 SMP Thu Mar 29 16:52:18
BST 2018 armv7l GNU/Linux
```

**sudo lsb_release -a**
```
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

**Comment by E3V3A** [comment]
Hi @FLASH980 

1. Please update your npm and nodejs!
2. Please upload another screenshot, that one is too small to read!
3. If Google API  tell you there is a permission issue, then that's what it is. You have probably forgotten (or not seen) some permission related thing that you need to enable in there. Please check your google developer console again and go through the Wiki step-by step.

**Comment by E3V3A** [comment]
@FLASH980 Any news? 
Perhaps you have exceeded your free request quota? 
Please reopen, if your issue is with this module.
