### ISSUE TITLE
Raspian Stretch Full Version

### ISSUE THREAD

**Issue by werdnllac** [eouia/MMM-Assistant#57]
Hi, anyone can direct me the link to download the full Raspian Stretch 9.4 version?

From https://github.com/eouia/MMM-Assistant, it is mentioned to implement MMM-Assistant using full version but at https://www.raspberrypi.org/downloads/raspbian/ there is only 
1. Raspbian Stretch with desktop
2. Raspbian Stretch Lite

Had done a search in Google but has no clue to download the correct version.

Thanks

**Comment by drftg** [comment]
My guess is that the desktop version is what they refer to as the full version. It is the version I used.

**Comment by werdnllac** [comment]
@drftg Thanks
