### ISSUE TITLE
Assistant frozen after GA wake word

### ISSUE THREAD

**Issue by cryptooth** [eouia/MMM-Assistant#58]
No detailed descrpiton. assistant frozen after GA wake word.
MM wake word working normally.

**Comment by E3V3A** [comment]
@cryptooth Please provide [the relevant info](https://github.com/eouia/MMM-Assistant/blob/master/docs/ISSUE_TEMPLATE.md) requested.  That issue template was created to help answering trouble just like yours! 

* What does these say?  
  `cat ~/.pm2/logs/mm-error-0.log`  
  `cat ~/.pm2/logs/mm-out-0.log` 
* What does your browser debug tools say? (`CTRL-SHIFT-I`)

Given that the MM wake word works, I suspect it is a GA account setup issue.  
Please reopen when you have the logs and checked your GA account settings.
