### ISSUE TITLE
modules not receiving notifications.

### ISSUE THREAD

**Issue by parata45** [eouia/MMM-Assistant#6]
Hi when ever i send a notification using sendNotification none of my other modules receive the notification and yet all my other modules are able to communicate with each other no problem using  sendNotification. I am only new to this so sorry if this is a stupid question.

**Comment by eouia** [comment]
@parata45 
Can you explain more detailed?
1) Which notification did you expect?
2) On which condition did you expect the notification is fired?
3) Can you tell me suspicious points?(e.g. codes or environments)
4) Does other functionality work well? (e.g. hot word detection, google assistant working, voice recognition)

In your terminal, try this;
```
cd ~/MagicMirror(your magic mirror directory)
npm start dev
```
Now, you can see your mirror and an additional browser dev console window. Is there any suspicious error message?(See the `Console` Tab)
Or any error suspicious error message on your terminal?

**Comment by parata45** [comment]
Hi thanks for the reply. I am trying to send a notification to a small music player module that changes the src for the img element in the dom when it receives the notification. all my other modules are able to send the notification and the music player receives them and changes the image as expected but I am lost as to why it wont receive notifications from this module. I am just using the SendNotification("") statement and have tried placing it in a few different functions but with no luck. I thought placing it in the '''javascript
 case 'HOTWORD_DETECTED':
        this.status = "HOTWORD_DETECTED"
        console.log("[ASSTNT] Hotword detected:", payload)
        this.hotwordDetected(payload)
        this.sendNotification("HIDE_WEATHER")
        break
'''
but no luck. Other than that your module works fine for me I have no problem adding commands it also detects hotwords and the voice recognition is perfect and so is google assistant.

**Comment by eouia** [comment]
Hmmm. It sounds so strange. I think it should work.
I tried your code on my device.

https://www.dropbox.com/s/n0nne1deba75ta1/2017-10-13-095906_1920x1080_scrot.png?dl=0
You can see notification worked on right bottom. (`MMM-XXX... received notification: HIDE_WEATHER from sender: MMM-Assistant`)

**Comment by parata45** [comment]
Ok thanks for that I did notice the other day that my dev window stoped displaying all notifications from all modules but the notifications were still getting through to the modules so I am thinking a fresh install of the MagicMirror might help me out. anyway thanks for replying and comfirming its not your module at fault as now i can start trying something else to fix my problem. Thanks alot and thanks for producing a awsome module.

**Comment by eouia** [comment]
I wish your luck.
I'll close this.
